function gazepositions = importfileGazePositions(filename, dataLines)
%IMPORTFILE Import data from a text file
%  GAZEPOSITIONS = IMPORTFILE(FILENAME) reads data from text file
%  FILENAME for the default selection.  Returns the data as a table.
%
%  GAZEPOSITIONS = IMPORTFILE(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  gazepositions = importfile("C:\Users\Cassie\Documents\Masters Research Project\Coding Project\Data\Eye Trackers\2021-01-11_12-38-09-3a9fdfde\exports\000\gaze_positions.csv", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB 

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Setup the Import Options
opts = delimitedTextImportOptions("NumVariables", 21);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["gaze_timestamp", "world_index", "confidence", "norm_pos_x", "norm_pos_y", "base_data", "gaze_point_3d_x", "gaze_point_3d_y", "gaze_point_3d_z", "eye_center0_3d_x", "eye_center0_3d_y", "eye_center0_3d_z", "gaze_normal0_x", "gaze_normal0_y", "gaze_normal0_z", "eye_center1_3d_x", "eye_center1_3d_y", "eye_center1_3d_z", "gaze_normal1_x", "gaze_normal1_y", "gaze_normal1_z"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "char", "double", "double", "double", "char", "char", "char", "double", "double", "double", "char", "char", "char", "double", "double", "double"];
opts = setvaropts(opts, [6, 10, 11, 12, 16, 17, 18], "WhitespaceRule", "preserve");
opts = setvaropts(opts, [7, 8, 9, 13, 14, 15, 19, 20, 21], "TrimNonNumeric", true);
opts = setvaropts(opts, [7, 8, 9, 13, 14, 15, 19, 20, 21], "ThousandsSeparator", ",");
opts = setvaropts(opts, [6, 10, 11, 12, 16, 17, 18], "EmptyFieldRule", "auto");
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
gazepositions = readtable(filename, opts);

end