function pupilpositions = importfilePupilPositions(filename, dataLines)
%IMPORTFILE Import data from a text file
%  PUPILPOSITIONS = IMPORTFILE(FILENAME) reads data from text file
%  FILENAME for the default selection.  Returns the data as a table.
%
%  PUPILPOSITIONS = IMPORTFILE(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  pupilpositions = importfile("C:\Users\Cassie\Documents\Masters Research Project\Coding Project\Data\Eye Trackers\2021-01-11_12-38-09-3a9fdfde\exports\000\pupil_positions.csv", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 29-Apr-2021 18:36:05

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Setup the Import Options
opts = delimitedTextImportOptions("NumVariables", 34);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["pupil_timestamp", "world_index", "eye_id", "confidence", "norm_pos_x", "norm_pos_y", "diameter", "method", "ellipse_center_x", "ellipse_center_y", "ellipse_axis_a", "ellipse_axis_b", "ellipse_angle", "diameter_3d", "model_confidence", "model_id", "sphere_center_x", "sphere_center_y", "sphere_center_z", "sphere_radius", "circle_3d_center_x", "circle_3d_center_y", "circle_3d_center_z", "circle_3d_normal_x", "circle_3d_normal_y", "circle_3d_normal_z", "circle_3d_radius", "theta", "phi", "projected_sphere_center_x", "projected_sphere_center_y", "projected_sphere_axis_a", "projected_sphere_axis_b", "projected_sphere_angle"];
opts.VariableTypes = ["char", "char", "char", "char", "char", "char", "char", "char", "char", "char", "char", "char", "char", "char", "char", "char", "char", "char", "char", "char", "char", "char", "char", "char", "char", "char", "char", "char", "char", "char", "char", "char", "char", "char"];
opts = setvaropts(opts, [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34], "WhitespaceRule", "preserve");
opts = setvaropts(opts, [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34], "EmptyFieldRule", "auto");
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
pupilpositions = readtable(filename, opts);

end