function loadsol = importfileLoadsolData(filename, dataLines)
%IMPORTFILE Import data from a text file
%  LOADSOL = IMPORTFILE(FILENAME) reads data from
%  text file FILENAME for the default selection.  Returns the data as a
%  table.
%
%  LOADSOL = IMPORTFILE(FILE, DATALINES) reads data
%  for the specified row interval(s) of text file FILENAME. Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  loadsol = importfileLoadsolData("C:\Users\Cassie\Documents\Masters Research Project\Coding Project\Data\Loadsol\loadsolASCII_21-01-11 12-38-04-965.txt", [5, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [5, Inf];
end

%% Setup the Import Options
opts = delimitedTextImportOptions("NumVariables", 15);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = "\t";

% Specify column names and types
opts.VariableNames = ["VarName1", "Heel", "Medial", "Lateral", "PGW072L", "VarName6", "Lateral1", "Medial1", "Heel1", "PGW071R", "VarName11", "VarName12", "VarName13", "VarName14", "VarName15"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "char", "char", "char", "char", "char"];
opts = setvaropts(opts, [11, 12, 13, 14, 15], "WhitespaceRule", "preserve");
opts = setvaropts(opts, [11, 12, 13, 14, 15], "EmptyFieldRule", "auto");
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
loadsol = readtable(filename, opts);

end